import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";
import { SheetProvider } from "@/providers/sheet-provider";
import { Toaster } from "@/components/ui/sonner";

// Load custom fonts with variable weights
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata for the layout (title and description)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ClerkProvider wraps the app with authentication functionality
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* QueryProvider enables global data fetching with React Query */}
          <QueryProvider>
            {/* SheetProvider and Toaster provide UI components for notifications */}
            <SheetProvider/>
            <Toaster/>
            {children} {/* Render child components passed into the layout */}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
